### ISSUE TITLE
example/manipulation needs socket.oi@0.9

### ISSUE THREAD

**Issue by coderofsalvation** [thisconnect/port#14]
breaks with latest socket.io ('Transport Unknown' error).

Works with 'npm install socket.io@0.9'

Nevertheless: awesome module

**Comment by thisconnect** [comment]
Thanks. Yes examples could use some love. socket.io 1.x had some api changes. I guess "socket.io": "^0.9.17" should be added in the package.json as devDependencies. Care to send a pull request? :)

**Comment by thisconnect** [comment]
Alternatively the example probably should just use the latest socket.io versoin/api

**Comment by coderofsalvation** [comment]
agreed, 

updated package.json is here: https://github.com/thisconnect/port/pull/15
