### ISSUE TITLE
No tests currently working on pd 0.54-1

### ISSUE THREAD

**Issue by theslyprofessor** [thisconnect/port#20]
Hello,
I am trying to run the shipped tests on pd-0.54-1 but none of them work. I have no idea why. I am wondering if this is as a result of a change in PD as of 0.51 (see picture below). 

<img width="1049" alt="image" src="https://github.com/thisconnect/port/assets/20659937/3ac8ba1a-49ab-4e19-aa8c-9d5c7761285d">

Many thanks,
Nakul

**Comment by theslyprofessor** [comment]
I have been working on updating the code to be compliant with modern javascript. I think the next step is to create an external in PureData and then we'll have NodeForPureData!

**Comment by theslyprofessor** [comment]
I figured out why the tests weren't working...Now I'm working on improving code.

**Comment by thisconnect** [comment]
> I figured out why the tests weren't working

please comment what the issue was in case anyone else runs into this.
